Repository singh-odyssey/travellers, pull requests merged in 2025-09, with the labels that each got.

#13 Testing branch 2
  README.md
Labels: test-only

#14 Update Landing page
  src/app/layout.tsx
  src/app/page.tsx
  src/components/site-footer.tsx
  src/components/site-header.tsx
Labels: enhancement

#15 Update readme
  README.md
Labels: documentation, enhancement

#28 fix #21
  package-lock.json
  package.json
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/upload/page.tsx
  src/components/sign-in-form.tsx
  src/components/sign-up-form.tsx
  src/components/site-footer.tsx
  src/components/site-header.tsx
  src/components/theme-wrapper.tsx
  src/components/ticket-upload-form.tsx
  src/components/toggle.tsx
  src/state/theme.tsx
  tailwind.config.ts
Labels: enhancement, level3
